FROM python:3.9-slim

RUN useradd impatient
WORKDIR /home/impatient

RUN apt update && apt install -y gcc git tesseract-ocr tesseract-ocr-osd tesseract-ocr-fra poppler-utils
COPY --chown=impatient:impatient pyproject.toml pyproject.toml
COPY --chown=impatient:impatient poetry.lock poetry.lock

RUN python -m pip install poetry
RUN python -m poetry config virtualenvs.create false
RUN python -m poetry install --no-root --no-interaction && rm -rf ~/.cache/pypoetry/{cache,artifacts}

RUN chown impatient:impatient /home/impatient

ENV FLASK_ENV development
ENV FLASK_APP impatient.py
ENV SHELL /bin/bash

USER impatient

EXPOSE 5000
ENTRYPOINT ["./dev_boot.sh"]
