FROM python:3.9-slim

RUN useradd ehroes
WORKDIR /home/ehroes

RUN apt update && apt install -y gcc git tesseract-ocr tesseract-ocr-osd tesseract-ocr-fra poppler-utils
COPY --chown=ehroes:ehroes pyproject.toml pyproject.toml
COPY --chown=ehroes:ehroes poetry.lock poetry.lock

RUN python -m pip install poetry
RUN python -m poetry config virtualenvs.create false
RUN python -m poetry install --no-root --no-interaction && rm -rf ~/.cache/pypoetry/{cache,artifacts}

RUN chown ehroes:ehroes /home/ehroes

ENV FLASK_ENV development
ENV FLASK_APP ehroes.py
ENV SHELL /bin/bash

USER ehroes

EXPOSE 5000
ENTRYPOINT ["./dev_boot.sh"]
