"""Bland to blend

Revision ID: 78a123694ce2
Revises: e6337fb0fc1c
Create Date: 2022-02-10 11:21:13.884534

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "78a123694ce2"
down_revision = "e6337fb0fc1c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('sqlite_sequence')
    with op.batch_alter_table("image", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("blend_image_path", sa.String(length=4096), nullable=True)
        )
        batch_op.drop_constraint("uq_image_bland_image_path", type_="unique")
        batch_op.create_unique_constraint(
            batch_op.f("uq_image_blend_image_path"), ["blend_image_path"]
        )
        batch_op.drop_column("bland_image_path")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("image", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("bland_image_path", sa.VARCHAR(length=4096), nullable=True)
        )
        batch_op.drop_constraint(
            batch_op.f("uq_image_blend_image_path"), type_="unique"
        )
        batch_op.create_unique_constraint(
            "uq_image_bland_image_path", ["bland_image_path"]
        )
        batch_op.drop_column("blend_image_path")

    # op.create_table('sqlite_sequence',
    # sa.Column('name', sa.NullType(), nullable=True),
    # sa.Column('seq', sa.NullType(), nullable=True)
    # )
    # ### end Alembic commands ###
