"""empty message

Revision ID: cc394f0a8f7d
Revises: b27118dec823
Create Date: 2025-06-23 10:15:40.155812

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'cc394f0a8f7d'
down_revision = 'b27118dec823'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.drop_index(batch_op.f('ix_user_username'))

    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_image_expert_id_user'), type_='foreignkey')
        batch_op.drop_column('expert_id')

    with op.batch_alter_table('report_histo', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_report_histo_expert_id_user'), type_='foreignkey')
        batch_op.drop_column('expert_id')

    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_histo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expert_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_report_histo_expert_id_user'), 'user', ['expert_id'], ['id'])

    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expert_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_image_expert_id_user'), 'user', ['expert_id'], ['id'])

    op.create_table('user',
                    sa.Column('id', sa.INTEGER(), nullable=False),
                    sa.Column('username', sa.VARCHAR(length=64), nullable=False),
                    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
                    sa.Column('password_hash', sa.VARCHAR(length=128), nullable=False),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_user'))
                    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=1)
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=1)

    # ### end Alembic commands ###
