"""rename column tree

Revision ID: 149b26239198
Revises: 847f2a6b8036
Create Date: 2021-03-19 16:50:32.687903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '149b26239198'
down_revision = '847f2a6b8036'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_histo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ontology_tree', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_histo', schema=None) as batch_op:
        batch_op.drop_column('ontology_tree')

    # ### end Alembic commands ###
