"""initial db

Revision ID: 1a883c035a44
Revises: 
Create Date: 2021-01-30 19:21:34.477399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a883c035a44'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('patient_firstname', sa.String(length=140), nullable=True),
    sa.Column('patient_name', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_patient_name'), 'patient', ['patient_name'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_name', sa.String(length=140), nullable=True),
    sa.Column('expert_id', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.String(length=100), nullable=True),
    sa.Column('image_binary', sa.LargeBinary(), nullable=True),
    sa.Column('diagnostic', sa.String(length=140), nullable=True),
    sa.Column('report_text', sa.Text(), nullable=True),
    sa.Column('annotation_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['expert_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_diagnostic'), 'image', ['diagnostic'], unique=False)
    op.create_index(op.f('ix_image_image_name'), 'image', ['image_name'], unique=False)
    op.create_table('pdf',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pdf_name', sa.String(length=140), nullable=True),
    sa.Column('expert_id', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.String(length=100), nullable=True),
    sa.Column('pdf_binary', sa.LargeBinary(), nullable=True),
    sa.Column('lang', sa.String(length=140), nullable=True),
    sa.Column('ocr_text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['expert_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pdf_lang'), 'pdf', ['lang'], unique=False)
    op.create_index(op.f('ix_pdf_pdf_name'), 'pdf', ['pdf_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pdf_pdf_name'), table_name='pdf')
    op.drop_index(op.f('ix_pdf_lang'), table_name='pdf')
    op.drop_table('pdf')
    op.drop_index(op.f('ix_image_image_name'), table_name='image')
    op.drop_index(op.f('ix_image_diagnostic'), table_name='image')
    op.drop_table('image')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_patient_patient_name'), table_name='patient')
    op.drop_table('patient')
    # ### end Alembic commands ###
