"""initial migration

Revision ID: 5109bd33a974
Revises: 
Create Date: 2021-04-05 01:37:23.878549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5109bd33a974'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_name', sa.String(length=140), nullable=True),
    sa.Column('expert_id', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.String(length=100), nullable=True),
    sa.Column('type_coloration', sa.String(length=140), nullable=True),
    sa.Column('age_at_biopsy', sa.Integer(), nullable=True),
    sa.Column('image_path', sa.String(length=4096), nullable=True),
    sa.Column('diagnostic', sa.String(length=140), nullable=True),
    sa.Column('report_text', sa.Text(), nullable=True),
    sa.Column('annotation_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['expert_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_image_diagnostic'), ['diagnostic'], unique=False)
        batch_op.create_index(batch_op.f('ix_image_image_name'), ['image_name'], unique=False)

    op.create_table('pdf',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pdf_name', sa.String(length=140), nullable=True),
    sa.Column('expert_id', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.String(length=100), nullable=True),
    sa.Column('pdf_path', sa.String(length=4096), nullable=True),
    sa.Column('lang', sa.String(length=140), nullable=True),
    sa.Column('ocr_text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['expert_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pdf', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pdf_lang'), ['lang'], unique=False)
        batch_op.create_index(batch_op.f('ix_pdf_pdf_name'), ['pdf_name'], unique=False)

    op.create_table('report_histo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.String(length=100), nullable=True),
    sa.Column('expert_id', sa.Integer(), nullable=True),
    sa.Column('biopsie_id', sa.String(length=140), nullable=True),
    sa.Column('muscle_prelev', sa.String(length=140), nullable=True),
    sa.Column('age_biopsie', sa.Integer(), nullable=True),
    sa.Column('date_envoie', sa.String(length=10), nullable=True),
    sa.Column('gene_diag', sa.String(length=140), nullable=True),
    sa.Column('ontology_tree', sa.JSON(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('conclusion', sa.String(length=140), nullable=True),
    sa.ForeignKeyConstraint(['expert_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('report_histo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_histo_biopsie_id'), ['biopsie_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_histo_conclusion'), ['conclusion'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_histo_patient_id'), ['patient_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_histo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_histo_patient_id'))
        batch_op.drop_index(batch_op.f('ix_report_histo_conclusion'))
        batch_op.drop_index(batch_op.f('ix_report_histo_biopsie_id'))

    op.drop_table('report_histo')
    with op.batch_alter_table('pdf', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pdf_pdf_name'))
        batch_op.drop_index(batch_op.f('ix_pdf_lang'))

    op.drop_table('pdf')
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_image_image_name'))
        batch_op.drop_index(batch_op.f('ix_image_diagnostic'))

    op.drop_table('image')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    # ### end Alembic commands ###
