"""Deleted PDF Table

Revision ID: 587c7acc5266
Revises: 5f7028c4e54c
Create Date: 2021-09-13 15:02:36.296633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "587c7acc5266"
down_revision = "5f7028c4e54c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("pdf", schema=None) as batch_op:
        batch_op.drop_index("ix_pdf_patient_id")
        batch_op.drop_index("ix_pdf_pdf_name")

    op.drop_table("pdf")
    # op.drop_table('sqlite_sequence')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sqlite_sequence",
        sa.Column("name", sa.NullType(), nullable=True),
        sa.Column("seq", sa.NullType(), nullable=True),
    )
    op.create_table(
        "pdf",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column(
            "pdf_name",
            sa.VARCHAR(length=140),
            server_default=sa.text("(NULL)"),
            nullable=False,
        ),
        sa.Column(
            "expert_id", sa.INTEGER(), server_default=sa.text("(NULL)"), nullable=False
        ),
        sa.Column(
            "patient_id",
            sa.VARCHAR(length=100),
            server_default=sa.text("(NULL)"),
            nullable=False,
        ),
        sa.Column(
            "pdf_path",
            sa.VARCHAR(length=4096),
            server_default=sa.text("(NULL)"),
            nullable=False,
        ),
        sa.Column(
            "lang",
            sa.VARCHAR(length=140),
            server_default=sa.text("(NULL)"),
            nullable=False,
        ),
        sa.Column("ocr_text", sa.TEXT(), nullable=True),
        sa.ForeignKeyConstraint(
            ["expert_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("pdf_path", name="uq_pdf_pdf_path"),
    )
    with op.batch_alter_table("pdf", schema=None) as batch_op:
        batch_op.create_index("ix_pdf_pdf_name", ["pdf_name"], unique=False)
        batch_op.create_index("ix_pdf_patient_id", ["patient_id"], unique=False)

    # ### end Alembic commands ###
