"""Segmentation File Path

Revision ID: 77cb4925bb52
Revises: ce2391642aea
Create Date: 2021-09-28 13:59:47.944913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "77cb4925bb52"
down_revision = "ce2391642aea"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('sqlite_sequence')
    with op.batch_alter_table("image", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("seg_matrix_path", sa.String(length=4096), nullable=True)
        )
        batch_op.add_column(
            sa.Column("mask_image_path", sa.String(length=4096), nullable=True)
        )
        batch_op.add_column(
            sa.Column("bland_image_path", sa.String(length=4096), nullable=True)
        )
        batch_op.add_column(
            sa.Column("classifier_path", sa.String(length=4096), nullable=True)
        )
        batch_op.create_unique_constraint(
            batch_op.f("uq_image_bland_image_path"), ["bland_image_path"]
        )
        batch_op.create_unique_constraint(
            batch_op.f("uq_image_classifier_path"), ["classifier_path"]
        )
        batch_op.create_unique_constraint(
            batch_op.f("uq_image_mask_image_path"), ["mask_image_path"]
        )
        batch_op.create_unique_constraint(
            batch_op.f("uq_image_seg_matrix_path"), ["seg_matrix_path"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("image", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("uq_image_seg_matrix_path"), type_="unique")
        batch_op.drop_constraint(batch_op.f("uq_image_mask_image_path"), type_="unique")
        batch_op.drop_constraint(batch_op.f("uq_image_classifier_path"), type_="unique")
        batch_op.drop_constraint(
            batch_op.f("uq_image_bland_image_path"), type_="unique"
        )
        batch_op.drop_column("classifier_path")
        batch_op.drop_column("bland_image_path")
        batch_op.drop_column("mask_image_path")
        batch_op.drop_column("seg_matrix_path")

    # op.create_table('sqlite_sequence',
    # sa.Column('name', sa.NullType(), nullable=True),
    # sa.Column('seq', sa.NullType(), nullable=True)
    # )
    # ### end Alembic commands ###
