"""DateTime for HistoReport

Revision ID: 836be1af53a7
Revises: 5109bd33a974
Create Date: 2021-04-12 10:45:04.773423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '836be1af53a7'
down_revision = '5109bd33a974'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_histo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('datetime', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_histo', schema=None) as batch_op:
        batch_op.drop_column('datetime')

    # ### end Alembic commands ###
