"""Image and Patient tables

Revision ID: 86d689db99f3
Revises: 24e69f864698
Create Date: 2020-12-17 11:39:57.160748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86d689db99f3'
down_revision = '24e69f864698'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_firstname', sa.String(length=140), nullable=True),
    sa.Column('patient_name', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_patient_name'), 'patient', ['patient_name'], unique=False)
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_name', sa.String(length=140), nullable=True),
    sa.Column('expert_name', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('image_binary', sa.LargeBinary(), nullable=True),
    sa.Column('diagnostic', sa.String(length=140), nullable=True),
    sa.Column('report_text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['expert_name'], ['user.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_diagnostic'), 'image', ['diagnostic'], unique=False)
    op.create_index(op.f('ix_image_image_name'), 'image', ['image_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_image_image_name'), table_name='image')
    op.drop_index(op.f('ix_image_diagnostic'), table_name='image')
    op.drop_table('image')
    op.drop_index(op.f('ix_patient_patient_name'), table_name='patient')
    op.drop_table('patient')
    # ### end Alembic commands ###
