"""empty message

Revision ID: 999561e3d610
Revises: f7ad27b89622
Create Date: 2021-01-13 10:47:28.435284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '999561e3d610'
down_revision = 'f7ad27b89622'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pdf',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pdf_name', sa.String(length=140), nullable=True),
    sa.Column('expert_id', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('pdf_binary', sa.LargeBinary(), nullable=True),
    sa.Column('lang', sa.String(length=140), nullable=True),
    sa.Column('ocr_text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['expert_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pdf_lang'), 'pdf', ['lang'], unique=False)
    op.create_index(op.f('ix_pdf_pdf_name'), 'pdf', ['pdf_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pdf_pdf_name'), table_name='pdf')
    op.drop_index(op.f('ix_pdf_lang'), table_name='pdf')
    op.drop_table('pdf')
    # ### end Alembic commands ###
