"""BOQA Field Score

Revision ID: a910926ae7e1
Revises: dd48a4e166ad
Create Date: 2021-10-14 12:02:05.208074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a910926ae7e1'
down_revision = 'dd48a4e166ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_table('sqlite_sequence')
    with op.batch_alter_table('report_histo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('BOQA_prediction_score', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_histo', schema=None) as batch_op:
        batch_op.drop_column('BOQA_prediction_score')

    #op.create_table('sqlite_sequence',
    #sa.Column('name', sa.NullType(), nullable=True),
    #sa.Column('seq', sa.NullType(), nullable=True)
    #)
    # ### end Alembic commands ###
