"""class info path for images

Revision ID: b27118dec823
Revises: 78a123694ce2
Create Date: 2022-03-24 17:54:11.594913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b27118dec823"
down_revision = "78a123694ce2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('sqlite_sequence')
    with op.batch_alter_table("image", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("class_info_path", sa.String(length=4096), nullable=True)
        )
        batch_op.create_unique_constraint(
            batch_op.f("uq_image_class_info_path"), ["class_info_path"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("image", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("uq_image_class_info_path"), type_="unique")
        batch_op.drop_column("class_info_path")

    # op.create_table('sqlite_sequence',
    # sa.Column('name', sa.NullType(), nullable=True),
    # sa.Column('seq', sa.NullType(), nullable=True)
    # )
    # ### end Alembic commands ###
