"""New Image Table

Revision ID: ce2391642aea
Revises: 587c7acc5266
Create Date: 2021-09-23 16:55:04.429326

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = "ce2391642aea"
down_revision = "587c7acc5266"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('sqlite_sequence')
    with op.batch_alter_table("image", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("biopsy_id", sa.String(length=100), nullable=True)
        )
        batch_op.create_index(
            batch_op.f("ix_image_biopsy_id"), ["biopsy_id"], unique=False
        )
        batch_op.drop_column("report_text")
        batch_op.drop_column("annotation_json")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("image", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "annotation_json",
                sqlite.JSON(),
                server_default=sa.text("(NULL)"),
                nullable=True,
            )
        )
        batch_op.add_column(sa.Column("report_text", sa.TEXT(), nullable=True))
        batch_op.drop_index(batch_op.f("ix_image_biopsy_id"))
        batch_op.drop_column("biopsy_id")

    # op.create_table('sqlite_sequence',
    # sa.Column('name', sa.NullType(), nullable=True),
    # sa.Column('seq', sa.NullType(), nullable=True)
    # )
    # ### end Alembic commands ###
