"""Added gene field to report

Revision ID: d23f27e36c11
Revises: 149b26239198
Create Date: 2021-03-22 15:23:45.558522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd23f27e36c11'
down_revision = '149b26239198'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_histo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gene_diag', sa.String(length=140), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_histo', schema=None) as batch_op:
        batch_op.drop_column('gene_diag')

    # ### end Alembic commands ###
