"""Update with new fields and date

Revision ID: d3f5d79b9f94
Revises: f7981800ac1e
Create Date: 2022-01-13 15:24:22.767508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d3f5d79b9f94"
down_revision = "f7981800ac1e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('sqlite_sequence')
    with op.batch_alter_table("image", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("image_background_path", sa.String(length=4096), nullable=True)
        )
        batch_op.add_column(sa.Column("sigma_range_min", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("datetime", sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint(
            batch_op.f("uq_image_image_background_path"), ["image_background_path"]
        )

    with op.batch_alter_table("report_histo", schema=None) as batch_op:
        batch_op.add_column(sa.Column("mutation", sa.String(length=140), nullable=True))
        batch_op.add_column(
            sa.Column("pheno_terms", sa.String(length=4096), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("report_histo", schema=None) as batch_op:
        batch_op.drop_column("pheno_terms")
        batch_op.drop_column("mutation")

    with op.batch_alter_table("image", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("uq_image_image_background_path"), type_="unique"
        )
        batch_op.drop_column("datetime")
        batch_op.drop_column("sigma_range_min")
        batch_op.drop_column("image_background_path")

    # op.create_table('sqlite_sequence',
    # sa.Column('name', sa.NullType(), nullable=True),
    # sa.Column('seq', sa.NullType(), nullable=True)
    # )
    # ### end Alembic commands ###
