"""BOQA Field

Revision ID: dd48a4e166ad
Revises: 4ce3b01f4706
Create Date: 2021-10-14 11:55:35.205467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd48a4e166ad'
down_revision = '4ce3b01f4706'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_table('sqlite_sequence')
    with op.batch_alter_table('report_histo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('BOQA_prediction', sa.String(length=140), nullable=True))
        batch_op.create_index(batch_op.f('ix_report_histo_BOQA_prediction'), ['BOQA_prediction'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_histo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_histo_BOQA_prediction'))
        batch_op.drop_column('BOQA_prediction')

    #op.create_table('sqlite_sequence',
    #sa.Column('name', sa.NullType(), nullable=True),
    #sa.Column('seq', sa.NullType(), nullable=True)
    #)
    # ### end Alembic commands ###
